# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnlockKeyboardTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MHAuthenticateNumberPad', :path => '../'

  # Pods for UnlockKeyboardTest

  target 'UnlockKeyboardTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
